# Site settings
title: Joel Graycar
email: j.cx.graycar@gmail.com
url: https://greytoyota.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
skills: "Full Stack Web Developer"

# Contact form: comment the line below if you want to stick with the default PHP contact form
contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Joel Graycar
  location: Location
  social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: github
    url: https://github.com/jgraycar
  - title: linkedin
    url: https://www.linkedin.com/in/jgraycar
  - title: google-plus
    url: https://plus.google.com/+JoelGraycar

# Postal address (add as many lines as necessary)
address:
  - line: Berkeley, CA

# Credits content
credits: 'Freelancer is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com">Start Bootstrap</a>.'

# Build settings
markdown: kramdown
permalink: pretty

# Career events
events:
  - image: "/img/career/yelp.png"
    date: "May 2015 - August 2015"
    description: "Software Engineering Intern @ Yelp, working on the <a href=\"http://seatme.yelp.com\" target=\"_blank\">SeatMe</a> team as a Full-Stack Web Developer."

  - image: "/img/career/berkeley_law.png"
    date: "June 2014 - February 2015"
    description: "Student Web Applications Programmer @ <a href=\"http://www.law.berkeley.edu\" target=\"_blank\">Berkeley Law School</a>."

  - image: "/img/career/decision_next.png"
    date: "May 2013 - September 2013"
    description: "Data Analysis Intern @ <a href=\"http://decisionnext.com/\" target=\"_blank\">DecisionNext</a>."

  - image: "/img/career/caltaiko.png"
    date: "September 2012 - Today"
    description: "Performing Member of <a href=\"http://www.caltaiko.org\" target=\"_blank\">Cal Raijin Taiko</a>. Over four years served as Performance Coordinator, Treasurer, Website Manager, and Director."

  - image: "/img/career/berkeley.png"
    date: "August 2012 - Today"
    description: "Undergraduate Student @ the <a href=\"https://www.berkeley.edu\" target=\"_blank\">University of California, Berkeley</a>, majoring in Computer Science."

# Default settings
defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
      client-url: '#'
